export const petCategoryOptions = [
    { value: "dog", label: "Dog" },
    { value: "cat", label: "Cat" },
    { value: "rabbit", label: "Rabbit" },
    { value: "hamster", label: "Hamster" },
    { value: "guinea_pig", label: "Guinea Pig" },
    { value: "ferret", label: "Ferret" },
    { value: "mouse", label: "Mouse" },
    { value: "rat", label: "Rat" },
    { value: "gerbil", label: "Gerbil" },
    { value: "chinchilla", label: "Chinchilla" },
    { value: "bird", label: "Bird" },
    { value: "parrot", label: "Parrot" },
    { value: "canary", label: "Canary" },
    { value: "finch", label: "Finch" },
    { value: "lovebird", label: "Lovebird" },
    { value: "cockatiel", label: "Cockatiel" },
    { value: "fish", label: "Fish" },
    { value: "goldfish", label: "Goldfish" },
    { value: "betta_fish", label: "Betta Fish" },
    { value: "tropical_fish", label: "Tropical Fish" },
    { value: "turtle", label: "Turtle" },
    { value: "tortoise", label: "Tortoise" },
    { value: "lizard", label: "Lizard" },
    { value: "gecko", label: "Gecko" },
    { value: "iguana", label: "Iguana" },
    { value: "snake", label: "Snake" },
    { value: "frog", label: "Frog" },
    { value: "toad", label: "Toad" },
    { value: "hedgehog", label: "Hedgehog" },
    { value: "sugar_glider", label: "Sugar Glider" },
    { value: "hermit_crab", label: "Hermit Crab" },
    { value: "chicken", label: "Chicken" },
    { value: "duck", label: "Duck" },
    { value: "pig", label: "Pig" },
    { value: "goat", label: "Goat" },
    { value: "horse", label: "Horse" },
    { value: "pony", label: "Pony" },
    { value: "donkey", label: "Donkey" },
    { value: "cow", label: "Cow" },
    { value: "sheep", label: "Sheep" },
    { value: "reptile", label: "Reptile" },
    { value: "amphibian", label: "Amphibian" },
    { value: "small_mammal", label: "Small Mammal" },
    { value: "farm_animal", label: "Farm Animal" },
    { value: "exotic_pet", label: "Exotic Pet" },
    { value: "other", label: "Other" },
];