export const petCategoryOptions = [
    { value: "dog", label: "Dog" },
    { value: "cat", label: "Cat" },
    { value: "rabbit", label: "Rabbit" },
    { value: "hamster", label: "Hamster" },
    { value: "guinea_pig", label: "Guinea Pig" },
    { value: "mouse", label: "Mouse" },
    { value: "bird", label: "Bird" },
    { value: "fish", label: "Fish" },
    { value: "turtle", label: "Turtle" },
    { value: "lizard", label: "Lizard" },
    { value: "frog", label: "Frog" },
    { value: "hedgehog", label: "Hedgehog" },
    { value: "sugar_glider", label: "Sugar Glider" },
    { value: "reptile", label: "Reptile" },
    { value: "exotic_pet", label: "Exotic Pet" },
    { value: "other", label: "Other" },
];
